version: '2'
services:
  web:
    build: gob/web
    container_name: web
    ports: ["8080:8080"]
    command: -gen-addr=linkerd:4140 -word-addr=linkerd:4140 -gen-name=linkerdexamples_gen -word-name=linkerdexamples_word

  gen:
    build: gob/gen
    container_name: gen
    hostname: gen
    ports: ["8181:8181"]

  word:
    build: gob/word
    container_name: word
    hostname: word
    ports: ["8282:8282"]

  consul:
    image: consul
    command: consul agent -dev -server -bootstrap -ui -client 0.0.0.0 -advertise 192.168.99.100
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8302:8302"
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
    
  registrator:
    image: gliderlabs/registrator:latest
    command: consul://consul:8500
    links:
      - consul
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock

  linkerd:
    image: buoyantio/linkerd:0.6.0
    container_name: linkerd
    ports: ["4140:4140", "9990:9990"]
    volumes:
      - "./config:/io.buoyant/linkerd/config:ro"
    command: /io.buoyant/linkerd/config/linkerd.yaml
    links:
      - consul
      - namerd

  namerd:
    image: buoyantio/namerd:0.6.0
    container_name: namerd
    ports: ["4100:4100", "4180:4180", "9991:9991"]
    volumes: ["./config:/io.buoyant/linkerd/config:ro"]
    command: /io.buoyant/linkerd/config/namerd.yaml
    links:
      - consul
